In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests

In [5]:
from nba_api.stats.static import teams
nba_teams = teams.get_teams()
team_names = [team['full_name'] for team in nba_teams]
team_names.sort()
team_ids = [team['id'] for team in nba_teams]

In [6]:
from nba_api.stats.endpoints import leaguegamefinder
games = None
for ids in team_ids:
    if games is None:
        gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=ids)
        games = gamefinder.get_data_frames()[0]
    else:
        gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=ids)
        games = pd.concat([games, gamefinder.get_data_frames()[0]])

In [7]:
games.to_csv('raw_games.csv')

In [58]:
games.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 102157 entries, 0 to 2862
Data columns (total 28 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   SEASON_ID          102157 non-null  object
 1   TEAM_ID            102157 non-null  int64
 2   TEAM_ABBREVIATION  102157 non-null  object
 3   TEAM_NAME          102157 non-null  object
 4   GAME_ID            102157 non-null  object
 5   GAME_DATE          102157 non-null  object
 6   MATCHUP            102157 non-null  object
 7   WL                 102135 non-null  object
 8   MIN                102157 non-null  int64
 9   PTS                102157 non-null  int64
 10  FGM                102157 non-null  int64
 11  FGA                102157 non-null  int64
 12  FG_PCT             102150 non-null  float64
 13  FG3M               102157 non-null  int64
 14  FG3A               102155 non-null  float64
 15  FG3_PCT            101112 non-null  float64
 16  FTM                102157 non-null  int64
 17  FTA                102157 non-null  int64
 18  FT_PCT             102147 non-null  float64
 19  OREB               102153 non-null  float64
 20  DREB               102153 non-null  float64
 21  REB                102156 non-null  float64
 22  AST                102157 non-null  int64
 23  STL                102155 non-null  float64
 24  BLK                102157 non-null  int64
 25  TOV                102157 non-null  int64
 26  PF                 102157 non-null  int64
 27  PLUS_MINUS         72453 non-null   float64
dtypes: float64(9), int64(12), object(7)
memory usage: 22.6+ MB

In [59]:
games.sort_values(by='GAME_DATE', ascending=False)

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22022,1610612738,BOS,Boston Celtics,0022200969,2023-03-05,BOS vs. NYK,L,289,129,...,0.880,17.0,37.0,54.0,27,8.0,5,16,28,-2.0
0,22022,1610612746,LAC,LA Clippers,0022200970,2023-03-05,LAC vs. MEM,W,239,135,...,0.943,13.0,40.0,53.0,25,6.0,2,17,17,6.0
0,22022,1610612762,UTA,Utah Jazz,0022200968,2023-03-05,UTA @ OKC,L,240,119,...,0.815,12.0,27.0,39.0,30,5.0,8,16,25,-10.0
0,22022,1610612760,OKC,Oklahoma City Thunder,0022200968,2023-03-05,OKC vs. UTA,W,241,129,...,0.818,11.0,31.0,42.0,24,9.0,4,12,20,10.0
0,22022,1610612759,SAS,San Antonio Spurs,0022200967,2023-03-05,SAS @ HOU,L,240,110,...,0.619,13.0,22.0,35.0,23,5.0,4,15,20,-32.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3604,21983,1610612754,IND,Indiana Pacers,0028300001,1983-10-28,IND @ MIL,L,240,83,...,0.619,24.0,29.0,53.0,27,7.0,4,19,22,NaN
3482,21983,1610612764,WAS,Washington Bullets,0028300003,1983-10-28,WAS @ PHL,L,240,114,...,0.759,10.0,26.0,36.0,32,9.0,3,21,35,NaN
3623,21983,1610612760,SEA,Seattle SuperSonics,0028300004,1983-10-28,SEA vs. GOS,L,240,109,...,0.698,8.0,23.0,31.0,27,4.0,3,22,34,NaN
3823,21983,1610612747,LAL,Los Angeles Lakers,0028300002,1983-10-28,LAL @ KCK,W,240,117,...,0.760,9.0,29.0,38.0,22,6.0,5,17,16,NaN
3680,21983,1610612762,UTH,Utah Jazz,0028300009,1983-10-28,UTH @ DEN,L,240,125,...,0.781,10.0,27.0,37.0,32,6.0,8,7,30,NaN

In [60]:
games.groupby('TEAM_ID').apply(lambda x: x)

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22022,1610612737,ATL,Atlanta Hawks,0022200958,2023-03-04,ATL @ MIA,L,239,109,...,0.867,10.0,27.0,37.0,22,12.0,1,16,23,-8.0
1,22022,1610612737,ATL,Atlanta Hawks,0022200947,2023-03-03,ATL vs. POR,W,239,129,...,0.813,10.0,33.0,43.0,30,10.0,5,17,19,18.0
2,22022,1610612737,ATL,Atlanta Hawks,0022200923,2023-02-28,ATL vs. WAS,L,239,116,...,0.895,13.0,29.0,42.0,21,4.0,7,9,17,-3.0
3,22022,1610612737,ATL,Atlanta Hawks,0022200911,2023-02-26,ATL vs. BKN,W,240,129,...,0.821,13.0,33.0,46.0,20,7.0,2,15,18,2.0
4,22022,1610612737,ATL,Atlanta Hawks,0022200896,2023-02-24,ATL vs. CLE,W,240,136,...,0.913,5.0,37.0,42.0,28,7.0,8,14,21,17.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2858,21988,1610612766,CHH,Charlotte Hornets,0028800062,1988-11-12,CHH @ ATL,L,238,111,...,0.813,14.0,21.0,35.0,30,12.0,2,19,26,NaN
2859,21988,1610612766,CHH,Charlotte Hornets,0028800052,1988-11-11,CHH @ WAS,L,240,87,...,0.760,11.0,32.0,43.0,22,9.0,1,23,26,NaN
2860,21988,1610612766,CHH,Charlotte Hornets,0028800024,1988-11-08,CHH vs. LAC,W,240,117,...,0.738,17.0,38.0,55.0,28,9.0,1,17,31,NaN
2861,21988,1610612766,CHH,Charlotte Hornets,0028800015,1988-11-05,CHH @ DET,L,240,85,...,1.000,21.0,19.0,40.0,18,8.0,6,11,21,NaN
2862,21988,1610612766,CHH,Charlotte Hornets,0028800008,1988-11-04,CHH vs. CLE,L,240,93,...,0.650,7.0,24.0,31.0,27,8.0,1,24,25,NaN

In [61]:
games['TEAM_NAME'].unique()

array(['Atlanta Hawks', 'Boston Celtics', 'Cleveland Cavaliers',
       'New Orleans Pelicans', 'New Orleans Hornets',
       'New Orleans/Oklahoma City Hornets', 'Chicago Bulls',
       'Dallas Mavericks', 'Denver Nuggets', 'Golden State Warriors',
       'Houston Rockets', 'LA Clippers', 'Los Angeles Clippers',
       'San Diego Clippers', 'Los Angeles Lakers', 'Miami Heat',
       'Milwaukee Bucks', 'Minnesota Timberwolves', 'Brooklyn Nets',
       'New Jersey Nets', 'New York Knicks', 'Orlando Magic',
       'Indiana Pacers', 'Philadelphia 76ers', 'Phoenix Suns',
       'Portland Trail Blazers', 'Sacramento Kings', 'Kansas City Kings',
       'San Antonio Spurs', 'Oklahoma City Thunder',
       'Seattle SuperSonics', 'Toronto Raptors', 'Utah Jazz',
       'Memphis Grizzlies', 'Vancouver Grizzlies', 'Washington Wizards',
       'Washington Bullets', 'Detroit Pistons', 'Charlotte Hornets',
       'Charlotte Bobcats'], dtype=object)

In [10]:
game_ids = games['GAME_ID'].head(10).unique().tolist()

In [11]:
from nba_api.stats.endpoints import boxscoreadvancedv2

In [12]:
boxscores_advanced = boxscoreadvancedv2.BoxScoreAdvancedV2(game_id=game_ids[0])

The command above/below gets the advanced boxscore from a given game id

boxscores_advanced.get_data_frames()[0] returns the advanced boxscore broken up per player

boxscores_advanced.get_data_frames()[1] returns the advanced boxscore broken up per team

In [13]:
boxscores_advanced.get_data_frames()[1]

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,...,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,0022200974,1610612748,Heat,MIA,Miami,None,None,0.0,None,0.0,...,None,None,None,1.0,0.0,None,None,None,0,None
1,0022200974,1610612737,Hawks,ATL,Atlanta,None,None,0.0,None,0.0,...,None,None,None,1.0,0.0,None,None,None,0,None

In [14]:
boxscores_advanced = None
for game_id in game_ids:
    if boxscores_advanced is None:
        gamefinder = boxscoreadvancedv2.BoxScoreAdvancedV2(game_id=game_id)
        boxscores_advanced = gamefinder.get_data_frames()[1]
    else:
        gamefinder = boxscoreadvancedv2.BoxScoreAdvancedV2(game_id=game_id)
        boxscores_advanced = pd.concat([boxscores_advanced, gamefinder.get_data_frames()[1]])

In [15]:
boxscores_advanced

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,...,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,0022200974,1610612748,Heat,MIA,Miami,None,None,0.0,None,0.0,...,None,None,None,1.0,0.000,None,None,None,0,None
1,0022200974,1610612737,Hawks,ATL,Atlanta,None,None,0.0,None,0.0,...,None,None,None,1.0,0.000,None,None,None,0,None
0,0022200958,1610612748,Heat,MIA,Miami,240:00,115.7,117.0,111.0,110.1,...,20.0,0.584,0.628,1.0,0.196,99.66,99.5,82.92,100,0.545
1,0022200958,1610612737,Hawks,ATL,Atlanta,240:00,111.0,110.1,115.7,117.0,...,16.2,0.525,0.591,1.0,0.201,99.66,99.5,82.92,99,0.455
0,0022200947,1610612757,Trail Blazers,POR,Portland,240:00,105.9,107.8,122.8,125.2,...,17.5,0.546,0.579,1.0,0.199,104.92,103.0,85.83,103,0.417
1,0022200947,1610612737,Hawks,ATL,Atlanta,240:00,122.8,125.2,105.9,107.8,...,16.5,0.637,0.658,1.0,0.202,104.92,103.0,85.83,103,0.583
0,0022200923,1610612764,Wizards,WAS,Washington,240:00,120.4,125.3,119.1,119.6,...,9.5,0.526,0.562,1.0,0.199,98.08,96.0,80.0,95,0.52
1,0022200923,1610612737,Hawks,ATL,Atlanta,240:00,119.1,119.6,120.4,125.3,...,9.3,0.532,0.572,1.0,0.199,98.08,96.0,80.0,97,0.48
0,0022200911,1610612751,Nets,BKN,Brooklyn,240:00,122.4,121.0,122.5,125.2,...,9.5,0.575,0.637,1.0,0.199,104.54,104.0,86.67,105,0.514
1,0022200911,1610612737,Hawks,ATL,Atlanta,240:00,122.5,125.2,122.4,121.0,...,15.5,0.589,0.63,1.0,0.199,104.54,104.0,86.67,103,0.486
0,0022200896,1610612739,Cavaliers,CLE,Cleveland,240:00,116.9,115.5,130.6,132.0,...,10.7,0.528,0.591,1.0,0.200,102.94,103.0,85.83,103,0.403
1,0022200896,1610612737,Hawks,ATL,Atlanta,240:00,130.6,132.0,116.9,115.5,...,13.6,0.676,0.715,1.0,0.200,102.94,103.0,85.83,103,0.597
0,0022200876,1610612752,Knicks,NYK,New York,240:00,115.4,119.6,97.8,100.0,...,9.8,0.542,0.577,1.0,0.195,104.46,101.5,84.58,102,0.551
1,0022200876,1610612737,Hawks,ATL,Atlanta,240:00,97.8,100.0,115.4,119.6,...,5.0,0.438,0.475,1.0,0.198,104.46,101.5,84.58,101,0.449
0,0022200857,1610612766,Hornets,CHA,Charlotte,240:00,133.2,132.1,121.9,127.8,...,15.6,0.75,0.765,1.0,0.202,110.68,108.5,90.42,109,0.54
1,0022200857,1610612737,Hawks,ATL,Atlanta,240:00,121.9,127.8,133.2,132.1,...,11.1,0.542,0.589,1.0,0.198,110.68,108.5,90.42,108,0.46
0,0022200850,1610612759,Spurs,SAS,San Antonio,240:00,98.6,100.0,116.4,117.9,...,18.9,0.484,0.522,1.0,0.199,107.42,106.0,88.33,106,0.413
1,0022200850,1610612737,Hawks,ATL,Atlanta,240:00,116.4,117.9,98.6,100.0,...,9.4,0.534,0.561,1.0,0.201,107.42,106.0,88.33,106,0.587
0,0022200832,1610612756,Suns,PHX,Phoenix,240:00,106.2,104.9,109.6,114.9,...,10.8,0.494,0.542,1.0,0.197,103.32,101.5,84.58,102,0.501
1,0022200832,1610612737,Hawks,ATL,Atlanta,240:00,109.6,114.9,106.2,104.9,...,18.8,0.505,0.543,1.0,0.199,103.32,101.5,84.58,101,0.499

In [16]:
from nba_api.stats.endpoints import boxscoreplayertrackv2

In [17]:
boxscores = boxscoreplayertrackv2.BoxScorePlayerTrackV2(game_id=game_ids[0])

ReadTimeout: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)

In [71]:
boxscores.get_data_frames()[0]

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,SPD,...,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,FG_PCT,DFGM,DFGA,DFG_PCT
0,0022200958,1610612737,ATL,Atlanta,1629631,De'Andre Hunter,F,,30:18,4.00,...,2,3,0.667,4,7,0.571,0.599,1,1,1.000
1,0022200958,1610612737,ATL,Atlanta,1628381,John Collins,F,,16:13,4.15,...,0,1,0.000,1,3,0.333,0.250,0,2,0.000
2,0022200958,1610612737,ATL,Atlanta,203991,Clint Capela,C,,24:56,3.95,...,7,9,0.778,1,1,1.000,0.800,2,7,0.286
3,0022200958,1610612737,ATL,Atlanta,1627749,Dejounte Murray,G,,36:02,4.14,...,2,6,0.333,1,8,0.125,0.213,3,3,1.000
4,0022200958,1610612737,ATL,Atlanta,1629027,Trae Young,G,,32:17,3.92,...,1,4,0.250,1,9,0.111,0.153,0,0,0.000
5,0022200958,1610612737,ATL,Atlanta,203992,Bogdan Bogdanovic,,,26:06,4.19,...,2,3,0.667,2,6,0.333,0.444,3,3,1.000
6,0022200958,1610612737,ATL,Atlanta,1630180,Saddiq Bey,,,34:48,4.18,...,2,3,0.667,5,9,0.556,0.582,2,3,0.667
7,0022200958,1610612737,ATL,Atlanta,1630168,Onyeka Okongwu,,,23:04,4.27,...,3,4,0.750,1,1,1.000,0.800,4,5,0.800
8,0022200958,1610612737,ATL,Atlanta,1630552,Jalen Johnson,,,16:16,4.13,...,0,0,0.000,2,2,1.000,1.000,0,0,0.000
9,0022200958,1610612737,ATL,Atlanta,1628981,Bruno Fernando,,DNP - Coach's Decision,0:00,0.00,...,0,0,0.000,0,0,0.000,0.000,0,0,0.000
10,0022200958,1610612737,ATL,Atlanta,1631100,AJ Griffin,,DNP - Coach's Decision,0:00,0.00,...,0,0,0.000,0,0,0.000,0.000,0,0,0.000
11,0022200958,1610612737,ATL,Atlanta,1628988,Aaron Holiday,,DNP - Coach's Decision,0:00,0.00,...,0,0,0.000,0,0,0.000,0.000,0,0,0.000
12,0022200958,1610612737,ATL,Atlanta,1630249,Vit Krejci,,DNP - Coach's Decision,0:00,0.00,...,0,0,0.000,0,0,0.000,0.000,0,0,0.000
13,0022200958,1610612737,ATL,Atlanta,1629726,Garrison Mathews,,DNP - Coach's Decision,0:00,0.00,...,0,0,0.000,0,0,0.000,0.000,0,0,0.000
14,0022200958,1610612748,MIA,Miami,202710,Jimmy Butler,F,,33:58,3.95,...,3,6,0.500,2,2,1.000,0.625,3,3,1.000
15,0022200958,1610612748,MIA,Miami,201567,Kevin Love,F,,18:06,3.84,...,0,1,0.000,2,6,0.333,0.285,3,3,1.000
16,0022200958,1610612748,MIA,Miami,1628389,Bam Adebayo,C,,35:32,3.96,...,6,7,0.857,4,5,0.800,0.832,3,6,0.500
17,0022200958,1610612748,MIA,Miami,1629639,Tyler Herro,G,,38:17,4.27,...,3,8,0.375,5,13,0.385,0.381,1,1,1.000
18,0022200958,1610612748,MIA,Miami,1629216,Gabe Vincent,G,,31:52,4.39,...,0,2,0.000,3,8,0.375,0.299,0,1,0.000
19,0022200958,1610612748,MIA,Miami,203506,Victor Oladipo,,,21:30,4.04,...,1,3,0.333,1,4,0.250,0.285,0,0,0.000
20,0022200958,1610612748,MIA,Miami,203469,Cody Zeller,,,12:28,4.31,...,2,2,1.000,2,2,1.000,1.000,5,6,0.833
21,0022200958,1610612748,MIA,Miami,1628997,Caleb Martin,,,29:54,4.86,...,1,1,1.000,5,9,0.556,0.599,3,4,0.750
22,0022200958,1610612748,MIA,Miami,1629622,Max Strus,,,18:23,4.43,...,1,1,1.000,1,3,0.333,0.500,1,1,1.000
23,0022200958,1610612748,MIA,Miami,2617,Udonis Haslem,,DNP - Coach's Decision,0:00,0.00,...,0,0,0.000,0,0,0.000,0.000,0,0,0.000
24,0022200958,1610612748,MIA,Miami,1629312,Haywood Highsmith,,DNP - Coach's Decision,0:00,0.00,...,0,0,0.000,0,0,0.000,0.000,0,0,0.000
25,0022200958,1610612748,MIA,Miami,1629130,Duncan Robinson,,DNP - Coach's Decision,0:00,0.00,...,0,0,0.000,0,0,0.000,0.000,0,0,0.000

In [72]:
boxscores_advanced = None
for game_id in game_ids:
    if boxscores_advanced is None:
        gamefinder = boxscoreplayertrackv2.BoxScorePlayerTrackV2(game_id=game_id)
        boxscores_advanced = gamefinder.get_data_frames()[0]
    else:
        gamefinder = boxscoreplayertrackv2.BoxScorePlayerTrackV2(game_id=game_id)
        boxscores_advanced = pd.concat([boxscores_advanced, gamefinder.get_data_frames()[0]])

In [74]:
boxscores_advanced

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,SPD,...,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,FG_PCT,DFGM,DFGA,DFG_PCT
0,0022200958,1610612737,ATL,Atlanta,1629631,De'Andre Hunter,F,,30:18,4.00,...,2,3,0.667,4,7,0.571,0.599,1,1,1.000
1,0022200958,1610612737,ATL,Atlanta,1628381,John Collins,F,,16:13,4.15,...,0,1,0.000,1,3,0.333,0.250,0,2,0.000
2,0022200958,1610612737,ATL,Atlanta,203991,Clint Capela,C,,24:56,3.95,...,7,9,0.778,1,1,1.000,0.800,2,7,0.286
3,0022200958,1610612737,ATL,Atlanta,1627749,Dejounte Murray,G,,36:02,4.14,...,2,6,0.333,1,8,0.125,0.213,3,3,1.000
4,0022200958,1610612737,ATL,Atlanta,1629027,Trae Young,G,,32:17,3.92,...,1,4,0.250,1,9,0.111,0.153,0,0,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21,0022100968,1610612765,DET,Detroit,203482,Kelly Olynyk,,,17:29,3.99,...,3,4,0.750,0,0,0.000,0.750,1,1,1.000
22,0022100968,1610612765,DET,Detroit,203585,Rodney McGruder,,,13:48,4.28,...,0,1,0.000,0,2,0.000,0.000,1,1,1.000
23,0022100968,1610612765,DET,Detroit,1630587,Isaiah Livers,,,24:33,4.16,...,0,0,0.000,3,6,0.500,0.500,1,1,1.000
24,0022100968,1610612765,DET,Detroit,1628977,Hamidou Diallo,,DNP - Coach's Decision,0:00,0.00,...,0,0,0.000,0,0,0.000,0.000,0,0,0.000
25,0022100968,1610612765,DET,Detroit,1628402,Frank Jackson,,DNP - Coach's Decision,0:00,0.00,...,0,0,0.000,0,0,0.000,0.000,0,0,0.000