In [1]:
import pandas as pd
import numpy as np

In [2]:
boxscores_advanced = pd.read_pickle('boxscores_advanced_team_2000.pkl')

In [10]:
boxscores_advanced.head()

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,...,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
4,0022200973,1610612764,Wizards,WAS,Washington,240:00,108.5,111.0,119.8,114.7,...,9.0,0.463,0.490,1.0,0.198,99.98,101.0,84.17,100,0.443
5,0022200973,1610612749,Bucks,MIL,Milwaukee,240:00,119.8,114.7,108.5,111.0,...,11.8,0.602,0.631,1.0,0.201,99.98,101.0,84.17,102,0.557
6,0022200964,1610612747,Lakers,LAL,Los Angeles,240:00,109.0,114.1,100.1,106.1,...,9.1,0.500,0.540,1.0,0.197,104.30,99.0,82.50,99,0.556
7,0022200964,1610612744,Warriors,GSW,Golden State,240:00,100.1,106.1,109.0,114.1,...,13.1,0.495,0.531,1.0,0.197,104.30,99.0,82.50,99,0.444
8,0022200962,1610612756,Suns,PHX,Phoenix,240:00,130.0,134.0,127.6,128.6,...,9.3,0.618,0.650,1.0,0.200,99.36,97.5,81.25,97,0.539

In [7]:
boxscores_advanced.iloc[::2].reset_index(drop=True)

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,...,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,0022200973,1610612764,Wizards,WAS,Washington,240:00,108.5,111.0,119.8,114.7,...,9.0,0.463,0.490,1.0,0.198,99.98,101.0,84.17,100,0.443
1,0022200964,1610612747,Lakers,LAL,Los Angeles,240:00,109.0,114.1,100.1,106.1,...,9.1,0.500,0.540,1.0,0.197,104.30,99.0,82.50,99,0.556
2,0022200962,1610612756,Suns,PHX,Phoenix,240:00,130.0,134.0,127.6,128.6,...,9.3,0.618,0.650,1.0,0.200,99.36,97.5,81.25,97,0.539
3,0022200963,1610612754,Pacers,IND,Indiana,240:00,128.8,133.0,127.1,131.2,...,9.6,0.596,0.619,1.0,0.196,96.52,93.5,77.92,94,0.502
4,0022200967,1610612759,Spurs,SAS,San Antonio,240:00,105.5,106.8,136.9,136.5,...,14.6,0.522,0.538,1.0,0.196,104.00,103.5,86.25,103,0.328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,0012200049,1610612749,Bucks,MIL,Milwaukee,240:00,96.1,100.0,123.2,122.1,...,13.5,0.489,0.514,1.0,0.198,105.68,104.0,86.67,104,0.355
994,0012200043,1610612764,Wizards,WAS,Washington,240:00,113.3,118.4,107.6,111.5,...,12.2,0.548,0.572,1.0,0.198,100.90,97.0,80.83,98,0.559
995,0012200046,1610612756,Suns,PHX,Phoenix,240:00,105.7,109.4,107.2,111.5,...,14.6,0.500,0.557,1.0,0.199,99.58,96.0,80.00,96,0.517
996,0012200045,1610612748,Heat,MIA,Miami,240:00,108.8,111.3,100.5,102.8,...,15.1,0.511,0.560,1.0,0.199,108.96,106.5,88.75,106,0.550
997,0012200044,1610612755,76ers,PHI,Philadelphia,240:00,114.2,114.1,97.7,99.0,...,11.1,0.533,0.571,1.0,0.198,99.10,98.5,82.08,99,0.555

In [11]:
boxscores_advanced.iloc[1::2].reset_index(drop=True)

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,...,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,0022200973,1610612749,Bucks,MIL,Milwaukee,240:00,119.8,114.7,108.5,111.0,...,11.8,0.602,0.631,1.0,0.201,99.98,101.0,84.17,102,0.557
1,0022200964,1610612744,Warriors,GSW,Golden State,240:00,100.1,106.1,109.0,114.1,...,13.1,0.495,0.531,1.0,0.197,104.30,99.0,82.50,99,0.444
2,0022200962,1610612742,Mavericks,DAL,Dallas,240:00,127.6,128.6,130.0,134.0,...,10.2,0.591,0.672,1.0,0.197,99.36,97.5,81.25,98,0.461
3,0022200963,1610612741,Bulls,CHI,Chicago,240:00,127.1,131.2,128.8,133.0,...,16.1,0.676,0.718,1.0,0.198,96.52,93.5,77.92,93,0.498
4,0022200967,1610612745,Rockets,HOU,Houston,240:00,136.9,136.5,105.5,106.8,...,11.5,0.688,0.726,1.0,0.202,104.00,103.5,86.25,104,0.672
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,0012200049,1610612741,Bulls,CHI,Chicago,240:00,123.2,122.1,96.1,100.0,...,14.4,0.585,0.610,1.0,0.200,105.68,104.0,86.67,104,0.645
994,0012200043,1610612766,Hornets,CHA,Charlotte,240:00,107.6,111.5,113.3,118.4,...,18.8,0.494,0.561,1.0,0.199,100.90,97.0,80.83,96,0.441
995,0012200046,1610612743,Nuggets,DEN,Denver,240:00,107.2,111.5,105.7,109.4,...,12.5,0.518,0.547,1.0,0.200,99.58,96.0,80.00,96,0.483
996,0012200045,1610612745,Rockets,HOU,Houston,240:00,100.5,102.8,108.8,111.3,...,23.4,0.538,0.558,1.0,0.198,108.96,106.5,88.75,107,0.450
997,0012200044,1610612739,Cavaliers,CLE,Cleveland,240:00,97.7,99.0,114.2,114.1,...,18.4,0.468,0.514,1.0,0.198,99.10,98.5,82.08,98,0.445