In [15]:
from pysbr import *
from datetime import datetime

In [33]:
dt_start = datetime.strptime('2020-01-01', '%Y-%m-%d')
dt_end = datetime.strptime('2022-01-01', '%Y-%m-%d')
nba = NBA()
sb = Sportsbook()

In [34]:
e = EventsByDateRange(nba.league_id, dt_start, dt_end)

In [35]:
len(e.list())

2528

In [36]:
e.list()[0]['participants']

[{'participant id': 1168,
  'is home': False,
  'source': {'name': 'Toronto',
   'nickname': 'Raptors',
   'short name': 'Toronto',
   'abbreviation': 'TOR',
   'location': 'Toronto'}},
 {'participant id': 1155,
  'is home': True,
  'source': {'name': 'Houston',
   'nickname': 'Rockets',
   'short name': 'Houston',
   'abbreviation': 'HOU',
   'location': 'Houston'}}]

In [37]:
import pandas as pd

In [38]:
df_e = e.dataframe()

In [39]:
df_e.columns

Index(['sport id', 'league id', 'season id', 'event id', 'description',
       'location', 'country', 'event status', 'datetime', 'stadium type',
       'event group.event group id', 'event group.name', 'event group.alias',
       'participants.1.participant id', 'participants.1.is home',
       'participants.1.source.name', 'participants.1.source.nickname',
       'participants.1.source.short name',
       'participants.1.source.abbreviation', 'participants.1.source.location',
       'participants.2.participant id', 'participants.2.is home',
       'participants.2.source.name', 'participants.2.source.nickname',
       'participants.2.source.short name',
       'participants.2.source.abbreviation', 'participants.2.source.location',
       'scores.1.participant id', 'scores.1.period', 'scores.1.points scored',
       'scores.2.participant id', 'scores.2.period', 'scores.2.points scored',
       'scores.3.participant id', 'scores.3.period', 'scores.3.points scored',
       'scores.4.participant id', 'scores.4.period', 'scores.4.points scored',
       'scores.5.participant id', 'scores.5.period', 'scores.5.points scored',
       'scores.6.participant id', 'scores.6.period', 'scores.6.points scored',
       'scores.7.participant id', 'scores.7.period', 'scores.7.points scored',
       'scores.8.participant id', 'scores.8.period', 'scores.8.points scored',
       'scores.9.participant id', 'scores.9.period', 'scores.9.points scored',
       'scores.10.participant id', 'scores.10.period',
       'scores.10.points scored', 'scores.11.participant id',
       'scores.11.period', 'scores.11.points scored',
       'scores.12.participant id', 'scores.12.period',
       'scores.12.points scored', 'scores.13.participant id',
       'scores.13.period', 'scores.13.points scored',
       'scores.14.participant id', 'scores.14.period',
       'scores.14.points scored'],
      dtype='object')

In [14]:
df_e.to_csv('2020_jan_2023_march.csv')

In [40]:
dt_start_2 = datetime.strptime('2022-01-02', '%Y-%m-%d')
dt_end_2 = datetime.strptime('2023-03-05', '%Y-%m-%d')
e_2 = EventsByDateRange(nba.league_id, dt_start_2, dt_end_2)

In [41]:
df_e_2 = e_2.dataframe()

In [42]:
df_e_2

,sport id,league id,season id,event id,description,location,country,event status,datetime,stadium type,event group.event group id,event group.name,event group.alias,participants.1.participant id,participants.1.is home,participants.1.source.name,participants.1.source.nickname,participants.1.source.short name,participants.1.source.abbreviation,participants.1.source.location,participants.2.participant id,participants.2.is home,participants.2.source.name,participants.2.source.nickname,participants.2.source.short name,participants.2.source.abbreviation,participants.2.source.location,scores.1.participant id,scores.1.period,scores.1.points scored,scores.2.participant id,scores.2.period,scores.2.points scored,scores.3.participant id,scores.3.period,scores.3.points scored,scores.4.participant id,scores.4.period,scores.4.points scored,scores.5.participant id,scores.5.period,scores.5.points scored,scores.6.participant id,scores.6.period,scores.6.points scored,scores.7.participant id,scores.7.period,scores.7.points scored,scores.8.participant id,scores.8.period,scores.8.points scored,scores.9.participant id,scores.9.period,scores.9.points scored,scores.10.participant id,scores.10.period,scores.10.points scored,scores.11.participant id,scores.11.period,scores.11.points scored,scores.12.participant id,scores.12.period,scores.12.points scored,scores.13.participant id,scores.13.period,scores.13.points scored,scores.14.participant id,scores.14.period,scores.14.points scored
0,5,5,36546,4669307,Detroit Pistons@New Orleans,New Orleans,USA,complete,2022-10-08T07:00:00+07:00,Undefined,5696,PRE,None,1164,False,Detroit,Pistons,Detroit,DET,Detroit,1157,True,New Orleans,Pelicans,New Orleans,NOP,New Orleans,1157.0,4.0,23.0,1164.0,4.0,23.0,1157.0,3.0,25.0,1164.0,3.0,27.0,1157.0,2.0,33.0,1164.0,2.0,26.0,1157.0,1.0,26.0,1164.0,1.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5,5,35878,4639727,Milwaukee Bucks@Boston Celtics,Boston,USA,complete,2022-05-12T06:00:01+07:00,Undefined,53,PST,None,1165,False,Milwaukee,Bucks,Milwaukee,MIL,Milwaukee,1171,True,Boston,Celtics,Boston,BOS,Boston,1165.0,4.0,33.0,1171.0,4.0,21.0,1165.0,3.0,30.0,1171.0,3.0,32.0,1171.0,2.0,28.0,1165.0,2.0,19.0,1171.0,1.0,26.0,1165.0,1.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5,5,36546,4669974,Atlanta Hawks@Milwaukee Bucks,Abu Dhabi,United Arab Emirates,complete,2022-10-08T23:00:00+07:00,Undefined,5696,PRE,None,1165,True,Milwaukee,Bucks,Milwaukee,MIL,Milwaukee,1159,False,Atlanta,Hawks,Atlanta,ATL,Atlanta,1165.0,4.0,34.0,1159.0,4.0,22.0,1159.0,3.0,33.0,1165.0,3.0,20.0,1159.0,2.0,39.0,1165.0,2.0,30.0,1159.0,1.0,24.0,1165.0,1.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,5,36546,4667352,San Antonio@Brooklyn Nets,Brooklyn,USA,complete,2023-01-03T07:30:00+07:00,Undefined,8,REG,None,1169,True,Brooklyn,Nets,Brooklyn,BKN,Brooklyn,1153,False,San Antonio,Spurs,San Antonio,SAS,San Antonio,1169.0,4.0,31.0,1153.0,4.0,24.0,1153.0,3.0,32.0,1169.0,3.0,34.0,1169.0,2.0,37.0,1153.0,2.0,22.0,1169.0,1.0,37.0,1153.0,1.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,5,36546,4667794,Denver Nuggets@Indiana Pacers,Indianapolis,USA,complete,2022-11-10T07:00:00+07:00,Undefined,8,REG,None,1163,True,Indiana,Pacers,Indiana,IND,Indiana,1147,False,Denver,Nuggets,Denver,DEN,Denver,1163.0,4.0,24.0,1147.0,4.0,33.0,1147.0,3.0,33.0,1163.0,3.0,25.0,1163.0,2.0,43.0,1147.0,2.0,21.0,1163.0,1.0,27.0,1147.0,1.0,35.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1824,5,5,36546,4667830,Dallas Mavericks@Denver Nuggets,Denver,USA,complete,2023-02-16T09:00:00+07:00,Undefined,8,REG,None,1147,True,Denver,Nuggets,Denver,DEN,Denver,1154,False,Dallas,Mavericks,Dallas,DAL,Dallas,1154.0,4.0,35.0,1147.0,4.0,26.0,1147.0,3.0,31.0,1154.0,3.0,30.0,1147.0,2.0,35.0,1154.0,2.0,19.0,1147.0,1.0,26.0,1154.0,1.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1825,5,5,36546,4667920,Brooklyn Nets@Chicago Bulls,Chicago,USA,complete,2023-02-25T08:00:00+07:00,Undefined,8,REG,None,1169,False,Brooklyn,Nets,Brooklyn,BKN,Brooklyn,1167,True,Chicago,Bulls,Chicago,CHI,Chicago,1169.0,4.0,36.0,1167.0,4.0,34.0,1167.0,3.0,34.0,1169.0,3.0,22.0,1169.0,2.0,11.0,1167.0,2.0,30.0,1167.0,1.0,33.0,1169.0,1.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1826,5,5,36546,4667916,Oklahoma City@Phoenix Suns,Phoenix,USA,complete,2023-02-25T10:00:00+07:00,Undefined,8,REG,None,1149,True,Phoenix,Suns,Phoenix,PHX,Phoenix,1145,False,Oklahoma City,Thunder,Oklahoma City,OKC,Oklahoma City,1149.0,4.0,30.0,1145.0,4.0,28.0,1149.0,3.0,29.0,1145.0,3.0,27.0,1149.0,2.0,36.0,1145.0,2.0,30.0,1145.0,1.0,30.0,1149.0,1.0,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1827,5,5,36546,4668002,Minnesota Timberwolves@Golden State,San Francisco,USA,complete,2023-02-27T07:30:00+07:00,Undefined,8,REG,None,1152,True,Golden State,Warriors,Golden State,GSW,Golden State,1144,False,Minnesota,Timberwolves,Minnesota,MIN,Minnesota,1152.0,4.0,31.0,1144.0,4.0,17.0,1144.0,3.0,30.0,1152.0,3.0,19.0,1152.0,2.0,34.0,1144.0,2.0,23.0,1144.0,1.0,34.0,1152.0,1.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1828,5,5,36546,4668171,Utah Jazz@Oklahoma City,Oklahoma City,USA,complete,2023-03-04T08:00:00+07:00,Undefined,8,REG,None,1145,True,Oklahoma City,Thunder,Oklahoma City,OKC,Oklahoma City,1143,False,Utah,Jazz,Utah,UTA,Utah,1143.0,4.0,19.0,1145.0,4.0,33.0,1145.0,3.0,30.0,1143.0,3.0,32.0,1145.0,2.0,33.0,1143.0,2.0,23.0,1145.0,1.0,34.0,1143.0,1.0,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
print(nba.sport_config())

{'default market id': 401, 'consensus market ids': [83, 401, 402], 'markets': [{'periods': 0, 'alias': '', 'market types': [{'alias': 'Money Lines', 'market id': 83, 'name': '2way (Including OT)', 'url': 'money-line'}, {'alias': 'Point Spreads', 'market id': 401, 'name': 'Point Spread (Including OT)', 'url': 'pointspread'}, {'alias': 'Totals', 'market id': 402, 'name': 'American Total (Including OT)', 'url': 'totals'}], 'market group id': 169, 'name': 'Full Game', 'url': 'full-game'}, {'periods': [1, 3], 'alias': '1st Half', 'market types': [{'alias': 'Money Lines', 'market id': 91, 'name': '1st Half - Draw No Bet', 'url': 'money-line'}, {'alias': 'Point Spreads', 'market id': 397, 'name': '1st Half - Point Spread', 'url': 'pointspread'}, {'alias': 'Totals', 'market id': 398, 'name': '1st Half - American Total', 'url': 'totals'}], 'market group id': 170, 'name': '1st Half', 'url': '1st-half'}, {'periods': [3, 5], 'alias': '2nd Half', 'market types': [{'alias': 'Money Lines', 'market id': 168, 'name': '2nd Half - Draw No Bet', 'url': 'money-line'}, {'alias': 'Point Spreads', 'market id': 399, 'name': '2nd Half - Point Spread', 'url': 'pointspread'}, {'alias': 'Totals', 'market id': 400, 'name': '2nd Half - American Total', 'url': 'totals'}], 'market group id': 171, 'name': '2nd Half', 'url': '2nd-half'}, {'periods': [1, 2], 'alias': '1Q', 'market types': [{'alias': 'Money Lines', 'market id': 93, 'name': '1st Period - Draw No Bet', 'url': 'money-line'}, {'alias': 'Point Spread', 'market id': 403, 'name': '1st Period - Point Spread', 'url': 'pointspread'}, {'alias': 'Totals', 'market id': 407, 'name': '1st Period - American Total', 'url': 'totals'}], 'market group id': 46, 'name': '1Q', 'url': '1st-quarter'}, {'periods': [2, 3], 'alias': '2Q', 'market types': [{'alias': 'Money Lines', 'market id': 97, 'name': '2nd Period - Draw No Bet', 'url': 'money-line'}, {'alias': 'Point Spreads', 'market id': 404, 'name': '2nd Period - Point Spread', 'url': 'pointspread'}, {'alias': 'Totals', 'market id': 408, 'name': '2nd Period - American Total', 'url': 'totals'}], 'market group id': 47, 'name': '2Q', 'url': '2nd-quarter'}, {'periods': [3, 4], 'alias': '3Q', 'market types': [{'alias': 'Money Lines', 'market id': 101, 'name': '3rd Period - Draw No Bet', 'url': 'money-line'}, {'alias': 'Point Spreads', 'market id': 405, 'name': '3rd Period - Point Spread', 'url': 'pointspread'}, {'alias': 'Totals', 'market id': 409, 'name': '3rd Period - American Total', 'url': 'totals'}], 'market group id': 48, 'name': '3Q', 'url': '3rd-quarter'}, {'periods': [4, 5], 'alias': '4Q', 'market types': [{'alias': 'Point Spreads', 'market id': 406, 'name': '4th Period - Point Spread', 'url': 'pointspread'}, {'alias': 'Money Lines', 'market id': 105, 'name': '4th Period - Draw No Bet', 'url': 'money-line'}, {'alias': 'Totals', 'market id': 410, 'name': '4th Period - American Total', 'url': 'totals'}], 'market group id': 49, 'name': '4Q', 'url': '4th-quarter'}, {'alias': 'Futures', 'market types': [{'alias': 'To Win Conference', 'market id': 338, 'name': 'To Win Conference', 'url': 'to-win-conference'}, {'alias': '', 'market id': 311, 'name': 'To Win Outright', 'url': 'to-win-outright'}], 'market group id': 176, 'name': 'Futures', 'url': 'future'}], 'sport id': 5}

In [44]:
ol = OpeningLines(e.ids(), nba.market_id('ps'), sb.id('Bovada'))

TransportServerError: 502 Server Error: Bad Gateway for url: https://ms.production-us-east-1.bookmakersreview.com/ms-odds-v2/odds-v2-service