In [15]:
from pysbr import *
from datetime import datetime

In [33]:
dt_start = datetime.strptime('2020-01-01', '%Y-%m-%d')
dt_end = datetime.strptime('2022-01-01', '%Y-%m-%d')
nba = NBA()
sb = Sportsbook()

In [51]:
sb.ids('pinnacle')

[20]

In [34]:
e = EventsByDateRange(nba.league_id, dt_start, dt_end)

In [57]:
len(e.list())

2528

In [36]:
e.list()[0]['participants']

[{'participant id': 1168,
  'is home': False,
  'source': {'name': 'Toronto',
   'nickname': 'Raptors',
   'short name': 'Toronto',
   'abbreviation': 'TOR',
   'location': 'Toronto'}},
 {'participant id': 1155,
  'is home': True,
  'source': {'name': 'Houston',
   'nickname': 'Rockets',
   'short name': 'Houston',
   'abbreviation': 'HOU',
   'location': 'Houston'}}]

In [37]:
import pandas as pd

In [38]:
df_e = e.dataframe()

In [39]:
df_e.columns

Index(['sport id', 'league id', 'season id', 'event id', 'description',
       'location', 'country', 'event status', 'datetime', 'stadium type',
       'event group.event group id', 'event group.name', 'event group.alias',
       'participants.1.participant id', 'participants.1.is home',
       'participants.1.source.name', 'participants.1.source.nickname',
       'participants.1.source.short name',
       'participants.1.source.abbreviation', 'participants.1.source.location',
       'participants.2.participant id', 'participants.2.is home',
       'participants.2.source.name', 'participants.2.source.nickname',
       'participants.2.source.short name',
       'participants.2.source.abbreviation', 'participants.2.source.location',
       'scores.1.participant id', 'scores.1.period', 'scores.1.points scored',
       'scores.2.participant id', 'scores.2.period', 'scores.2.points scored',
       'scores.3.participant id', 'scores.3.period', 'scores.3.points scored',
       'scores.4.participant id', 'scores.4.period', 'scores.4.points scored',
       'scores.5.participant id', 'scores.5.period', 'scores.5.points scored',
       'scores.6.participant id', 'scores.6.period', 'scores.6.points scored',
       'scores.7.participant id', 'scores.7.period', 'scores.7.points scored',
       'scores.8.participant id', 'scores.8.period', 'scores.8.points scored',
       'scores.9.participant id', 'scores.9.period', 'scores.9.points scored',
       'scores.10.participant id', 'scores.10.period',
       'scores.10.points scored', 'scores.11.participant id',
       'scores.11.period', 'scores.11.points scored',
       'scores.12.participant id', 'scores.12.period',
       'scores.12.points scored', 'scores.13.participant id',
       'scores.13.period', 'scores.13.points scored',
       'scores.14.participant id', 'scores.14.period',
       'scores.14.points scored'],
      dtype='object')

In [14]:
df_e.to_csv('2020_jan_2023_march.csv')

In [40]:
dt_start_2 = datetime.strptime('2022-01-02', '%Y-%m-%d')
dt_end_2 = datetime.strptime('2023-03-05', '%Y-%m-%d')
e_2 = EventsByDateRange(nba.league_id, dt_start_2, dt_end_2)

In [41]:
df_e_2 = e_2.dataframe()

In [42]:
df_e_2

,sport id,league id,season id,event id,description,location,country,event status,datetime,stadium type,event group.event group id,event group.name,event group.alias,participants.1.participant id,participants.1.is home,participants.1.source.name,participants.1.source.nickname,participants.1.source.short name,participants.1.source.abbreviation,participants.1.source.location,participants.2.participant id,participants.2.is home,participants.2.source.name,participants.2.source.nickname,participants.2.source.short name,participants.2.source.abbreviation,participants.2.source.location,scores.1.participant id,scores.1.period,scores.1.points scored,scores.2.participant id,scores.2.period,scores.2.points scored,scores.3.participant id,scores.3.period,scores.3.points scored,scores.4.participant id,scores.4.period,scores.4.points scored,scores.5.participant id,scores.5.period,scores.5.points scored,scores.6.participant id,scores.6.period,scores.6.points scored,scores.7.participant id,scores.7.period,scores.7.points scored,scores.8.participant id,scores.8.period,scores.8.points scored,scores.9.participant id,scores.9.period,scores.9.points scored,scores.10.participant id,scores.10.period,scores.10.points scored,scores.11.participant id,scores.11.period,scores.11.points scored,scores.12.participant id,scores.12.period,scores.12.points scored,scores.13.participant id,scores.13.period,scores.13.points scored,scores.14.participant id,scores.14.period,scores.14.points scored
0,5,5,36546,4669307,Detroit Pistons@New Orleans,New Orleans,USA,complete,2022-10-08T07:00:00+07:00,Undefined,5696,PRE,None,1164,False,Detroit,Pistons,Detroit,DET,Detroit,1157,True,New Orleans,Pelicans,New Orleans,NOP,New Orleans,1157.0,4.0,23.0,1164.0,4.0,23.0,1157.0,3.0,25.0,1164.0,3.0,27.0,1157.0,2.0,33.0,1164.0,2.0,26.0,1157.0,1.0,26.0,1164.0,1.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5,5,35878,4639727,Milwaukee Bucks@Boston Celtics,Boston,USA,complete,2022-05-12T06:00:01+07:00,Undefined,53,PST,None,1165,False,Milwaukee,Bucks,Milwaukee,MIL,Milwaukee,1171,True,Boston,Celtics,Boston,BOS,Boston,1165.0,4.0,33.0,1171.0,4.0,21.0,1165.0,3.0,30.0,1171.0,3.0,32.0,1171.0,2.0,28.0,1165.0,2.0,19.0,1171.0,1.0,26.0,1165.0,1.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5,5,36546,4669974,Atlanta Hawks@Milwaukee Bucks,Abu Dhabi,United Arab Emirates,complete,2022-10-08T23:00:00+07:00,Undefined,5696,PRE,None,1165,True,Milwaukee,Bucks,Milwaukee,MIL,Milwaukee,1159,False,Atlanta,Hawks,Atlanta,ATL,Atlanta,1165.0,4.0,34.0,1159.0,4.0,22.0,1159.0,3.0,33.0,1165.0,3.0,20.0,1159.0,2.0,39.0,1165.0,2.0,30.0,1159.0,1.0,24.0,1165.0,1.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,5,36546,4667352,San Antonio@Brooklyn Nets,Brooklyn,USA,complete,2023-01-03T07:30:00+07:00,Undefined,8,REG,None,1169,True,Brooklyn,Nets,Brooklyn,BKN,Brooklyn,1153,False,San Antonio,Spurs,San Antonio,SAS,San Antonio,1169.0,4.0,31.0,1153.0,4.0,24.0,1153.0,3.0,32.0,1169.0,3.0,34.0,1169.0,2.0,37.0,1153.0,2.0,22.0,1169.0,1.0,37.0,1153.0,1.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,5,36546,4667794,Denver Nuggets@Indiana Pacers,Indianapolis,USA,complete,2022-11-10T07:00:00+07:00,Undefined,8,REG,None,1163,True,Indiana,Pacers,Indiana,IND,Indiana,1147,False,Denver,Nuggets,Denver,DEN,Denver,1163.0,4.0,24.0,1147.0,4.0,33.0,1147.0,3.0,33.0,1163.0,3.0,25.0,1163.0,2.0,43.0,1147.0,2.0,21.0,1163.0,1.0,27.0,1147.0,1.0,35.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1824,5,5,36546,4667830,Dallas Mavericks@Denver Nuggets,Denver,USA,complete,2023-02-16T09:00:00+07:00,Undefined,8,REG,None,1147,True,Denver,Nuggets,Denver,DEN,Denver,1154,False,Dallas,Mavericks,Dallas,DAL,Dallas,1154.0,4.0,35.0,1147.0,4.0,26.0,1147.0,3.0,31.0,1154.0,3.0,30.0,1147.0,2.0,35.0,1154.0,2.0,19.0,1147.0,1.0,26.0,1154.0,1.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1825,5,5,36546,4667920,Brooklyn Nets@Chicago Bulls,Chicago,USA,complete,2023-02-25T08:00:00+07:00,Undefined,8,REG,None,1169,False,Brooklyn,Nets,Brooklyn,BKN,Brooklyn,1167,True,Chicago,Bulls,Chicago,CHI,Chicago,1169.0,4.0,36.0,1167.0,4.0,34.0,1167.0,3.0,34.0,1169.0,3.0,22.0,1169.0,2.0,11.0,1167.0,2.0,30.0,1167.0,1.0,33.0,1169.0,1.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1826,5,5,36546,4667916,Oklahoma City@Phoenix Suns,Phoenix,USA,complete,2023-02-25T10:00:00+07:00,Undefined,8,REG,None,1149,True,Phoenix,Suns,Phoenix,PHX,Phoenix,1145,False,Oklahoma City,Thunder,Oklahoma City,OKC,Oklahoma City,1149.0,4.0,30.0,1145.0,4.0,28.0,1149.0,3.0,29.0,1145.0,3.0,27.0,1149.0,2.0,36.0,1145.0,2.0,30.0,1145.0,1.0,30.0,1149.0,1.0,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1827,5,5,36546,4668002,Minnesota Timberwolves@Golden State,San Francisco,USA,complete,2023-02-27T07:30:00+07:00,Undefined,8,REG,None,1152,True,Golden State,Warriors,Golden State,GSW,Golden State,1144,False,Minnesota,Timberwolves,Minnesota,MIN,Minnesota,1152.0,4.0,31.0,1144.0,4.0,17.0,1144.0,3.0,30.0,1152.0,3.0,19.0,1152.0,2.0,34.0,1144.0,2.0,23.0,1144.0,1.0,34.0,1152.0,1.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1828,5,5,36546,4668171,Utah Jazz@Oklahoma City,Oklahoma City,USA,complete,2023-03-04T08:00:00+07:00,Undefined,8,REG,None,1145,True,Oklahoma City,Thunder,Oklahoma City,OKC,Oklahoma City,1143,False,Utah,Jazz,Utah,UTA,Utah,1143.0,4.0,19.0,1145.0,4.0,33.0,1145.0,3.0,30.0,1143.0,3.0,32.0,1145.0,2.0,33.0,1143.0,2.0,23.0,1145.0,1.0,34.0,1143.0,1.0,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
print(nba.sport_config())

{'default market id': 401, 'consensus market ids': [83, 401, 402], 'markets': [{'periods': 0, 'alias': '', 'market types': [{'alias': 'Money Lines', 'market id': 83, 'name': '2way (Including OT)', 'url': 'money-line'}, {'alias': 'Point Spreads', 'market id': 401, 'name': 'Point Spread (Including OT)', 'url': 'pointspread'}, {'alias': 'Totals', 'market id': 402, 'name': 'American Total (Including OT)', 'url': 'totals'}], 'market group id': 169, 'name': 'Full Game', 'url': 'full-game'}, {'periods': [1, 3], 'alias': '1st Half', 'market types': [{'alias': 'Money Lines', 'market id': 91, 'name': '1st Half - Draw No Bet', 'url': 'money-line'}, {'alias': 'Point Spreads', 'market id': 397, 'name': '1st Half - Point Spread', 'url': 'pointspread'}, {'alias': 'Totals', 'market id': 398, 'name': '1st Half - American Total', 'url': 'totals'}], 'market group id': 170, 'name': '1st Half', 'url': '1st-half'}, {'periods': [3, 5], 'alias': '2nd Half', 'market types': [{'alias': 'Money Lines', 'market id': 168, 'name': '2nd Half - Draw No Bet', 'url': 'money-line'}, {'alias': 'Point Spreads', 'market id': 399, 'name': '2nd Half - Point Spread', 'url': 'pointspread'}, {'alias': 'Totals', 'market id': 400, 'name': '2nd Half - American Total', 'url': 'totals'}], 'market group id': 171, 'name': '2nd Half', 'url': '2nd-half'}, {'periods': [1, 2], 'alias': '1Q', 'market types': [{'alias': 'Money Lines', 'market id': 93, 'name': '1st Period - Draw No Bet', 'url': 'money-line'}, {'alias': 'Point Spread', 'market id': 403, 'name': '1st Period - Point Spread', 'url': 'pointspread'}, {'alias': 'Totals', 'market id': 407, 'name': '1st Period - American Total', 'url': 'totals'}], 'market group id': 46, 'name': '1Q', 'url': '1st-quarter'}, {'periods': [2, 3], 'alias': '2Q', 'market types': [{'alias': 'Money Lines', 'market id': 97, 'name': '2nd Period - Draw No Bet', 'url': 'money-line'}, {'alias': 'Point Spreads', 'market id': 404, 'name': '2nd Period - Point Spread', 'url': 'pointspread'}, {'alias': 'Totals', 'market id': 408, 'name': '2nd Period - American Total', 'url': 'totals'}], 'market group id': 47, 'name': '2Q', 'url': '2nd-quarter'}, {'periods': [3, 4], 'alias': '3Q', 'market types': [{'alias': 'Money Lines', 'market id': 101, 'name': '3rd Period - Draw No Bet', 'url': 'money-line'}, {'alias': 'Point Spreads', 'market id': 405, 'name': '3rd Period - Point Spread', 'url': 'pointspread'}, {'alias': 'Totals', 'market id': 409, 'name': '3rd Period - American Total', 'url': 'totals'}], 'market group id': 48, 'name': '3Q', 'url': '3rd-quarter'}, {'periods': [4, 5], 'alias': '4Q', 'market types': [{'alias': 'Point Spreads', 'market id': 406, 'name': '4th Period - Point Spread', 'url': 'pointspread'}, {'alias': 'Money Lines', 'market id': 105, 'name': '4th Period - Draw No Bet', 'url': 'money-line'}, {'alias': 'Totals', 'market id': 410, 'name': '4th Period - American Total', 'url': 'totals'}], 'market group id': 49, 'name': '4Q', 'url': '4th-quarter'}, {'alias': 'Futures', 'market types': [{'alias': 'To Win Conference', 'market id': 338, 'name': 'To Win Conference', 'url': 'to-win-conference'}, {'alias': '', 'market id': 311, 'name': 'To Win Outright', 'url': 'to-win-outright'}], 'market group id': 176, 'name': 'Futures', 'url': 'future'}], 'sport id': 5}

In [170]:
ol_ps = OpeningLines(e.ids(), nba.market_id('pointspread'), sb.id('pinnacle'))

In [173]:
ol_t = OpeningLines(e.ids(), nba.market_id('Totals'), sb.id('pinnacle'))

In [175]:
ol_ml = OpeningLines(e.ids(), nba.market_id('money-line'), sb.id('pinnacle'))

In [176]:
df_olps = ol_ps.dataframe()
df_olt = ol_t.dataframe()
df_olml = ol_ml.dataframe()

In [177]:
df_ol = pd.concat([df_olt, df_olml, df_olps], axis=0)

In [178]:
df_e

,sport id,league id,season id,event id,description,location,country,event status,datetime,stadium type,event group.event group id,event group.name,event group.alias,participants.1.participant id,participants.1.is home,participants.1.source.name,participants.1.source.nickname,participants.1.source.short name,participants.1.source.abbreviation,participants.1.source.location,participants.2.participant id,participants.2.is home,participants.2.source.name,participants.2.source.nickname,participants.2.source.short name,participants.2.source.abbreviation,participants.2.source.location,scores.1.participant id,scores.1.period,scores.1.points scored,scores.2.participant id,scores.2.period,scores.2.points scored,scores.3.participant id,scores.3.period,scores.3.points scored,scores.4.participant id,scores.4.period,scores.4.points scored,scores.5.participant id,scores.5.period,scores.5.points scored,scores.6.participant id,scores.6.period,scores.6.points scored,scores.7.participant id,scores.7.period,scores.7.points scored,scores.8.participant id,scores.8.period,scores.8.points scored,scores.9.participant id,scores.9.period,scores.9.points scored,scores.10.participant id,scores.10.period,scores.10.points scored,scores.11.participant id,scores.11.period,scores.11.points scored,scores.12.participant id,scores.12.period,scores.12.points scored,scores.13.participant id,scores.13.period,scores.13.points scored,scores.14.participant id,scores.14.period,scores.14.points scored
0,5,5,25612,4341945,Toronto Raptors@Houston Rockets,Houston,USA,complete,2021-03-23T08:00:00+07:00,Undefined,8,REG,None,1168,False,Toronto,Raptors,Toronto,TOR,Toronto,1155,True,Houston,Rockets,Houston,HOU,Houston,1168.0,1.0,28.0,1155.0,1.0,27.0,1168.0,2.0,32.0,1155.0,2.0,38.0,1155.0,3.0,23.0,1168.0,3.0,26.0,1168.0,4.0,13.0,1155.0,4.0,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5,5,25612,4341949,Utah Jazz@Chicago Bulls,Chicago,USA,complete,2021-03-23T08:00:00+07:00,Undefined,8,REG,None,1167,True,Chicago,Bulls,Chicago,CHI,Chicago,1143,False,Utah,Jazz,Utah,UTA,Utah,1167.0,1.0,23.0,1143.0,1.0,29.0,1143.0,2.0,27.0,1167.0,2.0,19.0,1167.0,3.0,29.0,1143.0,3.0,33.0,1143.0,4.0,31.0,1167.0,4.0,24.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5,5,25612,4341951,Boston Celtics@Memphis Grizzlies,Memphis,USA,complete,2021-03-23T08:00:00+07:00,Undefined,8,REG,None,1156,True,Memphis,Grizzlies,Memphis,MEM,Memphis,1171,False,Boston,Celtics,Boston,BOS,Boston,1171.0,1.0,30.0,1156.0,1.0,24.0,1156.0,2.0,36.0,1171.0,2.0,35.0,1171.0,3.0,21.0,1156.0,3.0,34.0,1156.0,4.0,23.0,1171.0,4.0,31.0,1156.0,5.0,15.0,1171.0,5.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,5,25612,4341965,Philadelphia 76ers@Golden State,San Francisco,USA,complete,2021-03-24T09:00:00+07:00,Undefined,8,REG,None,1172,False,Philadelphia,76ers,Philadelphia,PHI,Philadelphia,1152,True,Golden State,Warriors,Golden State,GSW,Golden State,1172.0,1.0,35.0,1152.0,1.0,17.0,1172.0,2.0,24.0,1152.0,2.0,28.0,1152.0,3.0,40.0,1172.0,3.0,21.0,1152.0,4.0,13.0,1172.0,4.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,5,25612,4341972,Cleveland Cavaliers@Chicago Bulls,Chicago,USA,complete,2021-03-25T07:00:00+07:00,Undefined,8,REG,None,1166,False,Cleveland,Cavaliers,Cleveland,CLE,Cleveland,1167,True,Chicago,Bulls,Chicago,CHI,Chicago,1166.0,1.0,25.0,1167.0,1.0,25.0,1166.0,2.0,28.0,1167.0,2.0,30.0,1167.0,3.0,17.0,1166.0,3.0,25.0,1167.0,4.0,22.0,1166.0,4.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2523,5,5,35878,4532300,New Orleans@Utah Jazz,Salt Lake City,USA,complete,2021-11-28T09:00:00+07:00,Undefined,8,REG,None,1157,False,New Orleans,Pelicans,New Orleans,NOP,New Orleans,1143,True,Utah,Jazz,Utah,UTA,Utah,1157.0,4.0,38.0,1143.0,4.0,31.0,1143.0,3.0,32.0,1157.0,3.0,22.0,1157.0,2.0,22.0,1143.0,2.0,27.0,1157.0,1.0,23.0,1143.0,1.0,37.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2524,5,5,35878,4532307,Golden State@LA Clippers,Los Angeles,USA,complete,2021-11-29T03:30:00+07:00,Undefined,8,REG,None,1151,True,L.A. Clippers,L.A. Clippers,L.A. Clippers,LAC,LA,1152,False,Golden State,Warriors,Golden State,GSW,Golden State,1152.0,4.0,30.0,1151.0,4.0,22.0,1152.0,3.0,31.0,1151.0,3.0,26.0,1152.0,2.0,24.0,1151.0,2.0,18.0,1152.0,1.0,20.0,1151.0,1.0,24.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2525,5,5,35878,4532643,Utah Jazz@Philadelphia 76ers,Philadelphia,USA,complete,2021-12-10T07:00:00+07:00,Undefined,8,REG,None,1172,True,Philadelphia,76ers,Philadelphia,PHI,Philadelphia,1143,False,Utah,Jazz,Utah,UTA,Utah,1143.0,4.0,30.0,1172.0,4.0,20.0,1143.0,3.0,27.0,1172.0,3.0,22.0,1172.0,2.0,22.0,1143.0,2.0,34.0,1172.0,1.0,32.0,1143.0,1.0,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2526,5,5,35878,4532975,Houston Rockets@Indiana Pacers,Indianapolis,USA,complete,2021-12-24T07:00:00+07:00,Undefined,8,REG,None,1163,True,Indiana,Pacers,Indiana,IND,Indiana,1155,False,Houston,Rockets,Houston,HOU,Houston,1155.0,4.0,12.0,1163.0,4.0,27.0,1163.0,3.0,28.0,1155.0,3.0,36.0,1155.0,2.0,30.0,1163.0,2.0,27.0,1163.0,1.0,36.0,1155.0,1.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2527,5,5,35878,4532977,Atlanta Hawks@Philadelphia 76ers,Philadelphia,USA,complete,2021-12-24T07:00:00+07:00,Undefined,8,REG,None,1172,True,Philadelphia,76ers,Philadelphia,PHI,Philadelphia,1159,False,Atlanta,Hawks,Atlanta,ATL,Atlanta,1172.0,4.0,21.0,1159.0,4.0,19.0,1159.0,3.0,28.0,1172.0,3.0,24.0,1172.0,2.0,33.0,1159.0,2.0,19.0,1172.0,1.0,18.0,1159.0,1.0,32.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [180]:
merged_df = pd.merge(df_ol, df_e, how='inner', on='event id')[['event id', 'market id', 'description', 'location', 'datetime_x', 'decimal odds', 'american odds', 'spread / total', 'participants.1.participant id', 'participants.1.source.nickname', 'participants.1.source.short name', 'participants.2.participant id', 'participants.2.source.nickname', 'participants.2.source.short name']]

In [181]:
merged_df

,event id,market id,description,location,datetime_x,decimal odds,american odds,spread / total,participants.1.participant id,participants.1.source.nickname,participants.1.source.short name,participants.2.participant id,participants.2.source.nickname,participants.2.source.short name
0,3871405,402,Golden State@San Antonio,San Antonio,2019-12-31T04:01:48+07:00,1.9346,-107,220.0,1153,Spurs,San Antonio,1152,Warriors,Golden State
1,3871405,402,Golden State@San Antonio,San Antonio,2019-12-31T04:01:48+07:00,1.9346,-107,220.0,1153,Spurs,San Antonio,1152,Warriors,Golden State
2,3871405,83,Golden State@San Antonio,San Antonio,2019-12-31T04:01:48+07:00,4.5700,357,0.0,1153,Spurs,San Antonio,1152,Warriors,Golden State
3,3871405,83,Golden State@San Antonio,San Antonio,2019-12-31T04:01:48+07:00,1.2309,-433,0.0,1153,Spurs,San Antonio,1152,Warriors,Golden State
4,3871405,401,Golden State@San Antonio,San Antonio,2019-12-31T03:56:34+07:00,1.9524,-105,9.0,1153,Spurs,San Antonio,1152,Warriors,Golden State
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14700,4553153,83,Philadelphia 76ers@Toronto Raptors,Toronto,2021-10-04T19:02:11+07:00,2.1000,110,0.0,1172,76ers,Philadelphia,1168,Raptors,Toronto
14701,4553153,83,Philadelphia 76ers@Toronto Raptors,Toronto,2021-10-04T19:02:11+07:00,1.7752,-129,0.0,1172,76ers,Philadelphia,1168,Raptors,Toronto
14702,4553153,401,Philadelphia 76ers@Toronto Raptors,Toronto,2021-10-04T19:02:11+07:00,1.9259,-108,2.0,1172,76ers,Philadelphia,1168,Raptors,Toronto
14703,4553153,401,Philadelphia 76ers@Toronto Raptors,Toronto,2021-10-04T19:02:11+07:00,1.9259,-108,-2.0,1172,76ers,Philadelphia,1168,Raptors,Toronto
14704,4532344,83,Sacramento Kings@San Antonio,San Antonio,2021-11-10T05:49:35+07:00,1.9804,-102,0.0,1153,Spurs,San Antonio,1150,Kings,Sacramento

In [146]:
merged_df.to_csv('sportsbook_sample.csv')

In [183]:
ol2_ps = OpeningLines(e_2.ids(), nba.market_id('pointspread'), sb.id('pinnacle'))

In [185]:
ol2_t = OpeningLines(e_2.ids(), nba.market_id('Totals'), sb.id('pinnacle'))

In [187]:
ol2_ml = OpeningLines(e_2.ids(), nba.market_id('money-line'), sb.id('pinnacle'))

In [188]:
df2_olps = ol2_ps.dataframe()
df2_olt = ol2_t.dataframe()
df2_olml = ol2_ml.dataframe()

In [189]:
df2_olml

,entrid,mtgrp,market id,event id,sportsbook id,datetime,participant id,spread / total,decimal odds,american odds,team id
0,None,None,83,4531898,20,2022-03-11T21:36:13+07:00,1158,0,1.3774,-265,None
1,None,None,83,4531898,20,2022-03-11T21:36:13+07:00,1166,0,3.3100,231,None
2,None,None,83,4531900,20,2022-03-11T21:57:13+07:00,1143,0,1.5000,-200,None
3,None,None,83,4531900,20,2022-03-11T21:57:13+07:00,1153,0,2.7800,178,None
4,None,None,83,4531905,20,2022-03-11T21:15:50+07:00,1149,0,1.4785,-209,None
...,...,...,...,...,...,...,...,...,...,...,...
3639,None,None,83,4693181,20,2023-02-17T20:04:15+07:00,317684,0,1.6667,-150,None
3640,None,None,83,4693441,20,2023-02-18T08:19:21+07:00,588026,0,1.7692,-130,None
3641,None,None,83,4693441,20,2023-02-18T08:19:21+07:00,588027,0,2.1100,111,None
3642,None,None,83,4693444,20,2023-02-18T08:19:21+07:00,588028,0,2.4000,140,None
3643,None,None,83,4693444,20,2023-02-18T08:19:21+07:00,588029,0,1.6061,-165,None

In [190]:
df2_ol = pd.concat([df2_olt, df2_olml, df2_olps], axis=0)

In [191]:
df2_ol

,entrid,mtgrp,market id,event id,sportsbook id,datetime,participant id,spread / total,decimal odds,american odds,team id
0,None,None,402,4531898,20,2022-03-11T21:36:13+07:00,15143,211.0,1.9524,-105,None
1,None,None,402,4531898,20,2022-03-11T21:36:13+07:00,15144,211.0,1.9524,-105,None
2,None,None,402,4531900,20,2022-03-11T21:57:13+07:00,15143,229.0,1.9524,-105,None
3,None,None,402,4531900,20,2022-03-11T21:57:13+07:00,15144,229.0,1.9524,-105,None
4,None,None,402,4531905,20,2022-03-11T21:15:50+07:00,15143,222.0,1.9259,-108,None
...,...,...,...,...,...,...,...,...,...,...,...
3641,None,None,401,4669974,20,2022-10-08T19:09:40+07:00,1165,-2.5,1.9174,-109,None
3642,None,None,401,4669976,20,2022-10-11T19:04:12+07:00,1145,6.0,1.9346,-107,None
3643,None,None,401,4669976,20,2022-10-11T19:04:12+07:00,1164,-6.0,1.9174,-109,None
3644,None,None,401,4693181,20,2023-02-17T20:04:15+07:00,317683,3.0,1.9434,-106,None
3645,None,None,401,4693181,20,2023-02-17T20:04:15+07:00,317684,-3.0,1.9434,-106,None

In [192]:
df_e_2

,sport id,league id,season id,event id,description,location,country,event status,datetime,stadium type,event group.event group id,event group.name,event group.alias,participants.1.participant id,participants.1.is home,participants.1.source.name,participants.1.source.nickname,participants.1.source.short name,participants.1.source.abbreviation,participants.1.source.location,participants.2.participant id,participants.2.is home,participants.2.source.name,participants.2.source.nickname,participants.2.source.short name,participants.2.source.abbreviation,participants.2.source.location,scores.1.participant id,scores.1.period,scores.1.points scored,scores.2.participant id,scores.2.period,scores.2.points scored,scores.3.participant id,scores.3.period,scores.3.points scored,scores.4.participant id,scores.4.period,scores.4.points scored,scores.5.participant id,scores.5.period,scores.5.points scored,scores.6.participant id,scores.6.period,scores.6.points scored,scores.7.participant id,scores.7.period,scores.7.points scored,scores.8.participant id,scores.8.period,scores.8.points scored,scores.9.participant id,scores.9.period,scores.9.points scored,scores.10.participant id,scores.10.period,scores.10.points scored,scores.11.participant id,scores.11.period,scores.11.points scored,scores.12.participant id,scores.12.period,scores.12.points scored,scores.13.participant id,scores.13.period,scores.13.points scored,scores.14.participant id,scores.14.period,scores.14.points scored
0,5,5,36546,4669307,Detroit Pistons@New Orleans,New Orleans,USA,complete,2022-10-08T07:00:00+07:00,Undefined,5696,PRE,None,1164,False,Detroit,Pistons,Detroit,DET,Detroit,1157,True,New Orleans,Pelicans,New Orleans,NOP,New Orleans,1157.0,4.0,23.0,1164.0,4.0,23.0,1157.0,3.0,25.0,1164.0,3.0,27.0,1157.0,2.0,33.0,1164.0,2.0,26.0,1157.0,1.0,26.0,1164.0,1.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5,5,35878,4639727,Milwaukee Bucks@Boston Celtics,Boston,USA,complete,2022-05-12T06:00:01+07:00,Undefined,53,PST,None,1165,False,Milwaukee,Bucks,Milwaukee,MIL,Milwaukee,1171,True,Boston,Celtics,Boston,BOS,Boston,1165.0,4.0,33.0,1171.0,4.0,21.0,1165.0,3.0,30.0,1171.0,3.0,32.0,1171.0,2.0,28.0,1165.0,2.0,19.0,1171.0,1.0,26.0,1165.0,1.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5,5,36546,4669974,Atlanta Hawks@Milwaukee Bucks,Abu Dhabi,United Arab Emirates,complete,2022-10-08T23:00:00+07:00,Undefined,5696,PRE,None,1165,True,Milwaukee,Bucks,Milwaukee,MIL,Milwaukee,1159,False,Atlanta,Hawks,Atlanta,ATL,Atlanta,1165.0,4.0,34.0,1159.0,4.0,22.0,1159.0,3.0,33.0,1165.0,3.0,20.0,1159.0,2.0,39.0,1165.0,2.0,30.0,1159.0,1.0,24.0,1165.0,1.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,5,36546,4667352,San Antonio@Brooklyn Nets,Brooklyn,USA,complete,2023-01-03T07:30:00+07:00,Undefined,8,REG,None,1169,True,Brooklyn,Nets,Brooklyn,BKN,Brooklyn,1153,False,San Antonio,Spurs,San Antonio,SAS,San Antonio,1169.0,4.0,31.0,1153.0,4.0,24.0,1153.0,3.0,32.0,1169.0,3.0,34.0,1169.0,2.0,37.0,1153.0,2.0,22.0,1169.0,1.0,37.0,1153.0,1.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,5,36546,4667794,Denver Nuggets@Indiana Pacers,Indianapolis,USA,complete,2022-11-10T07:00:00+07:00,Undefined,8,REG,None,1163,True,Indiana,Pacers,Indiana,IND,Indiana,1147,False,Denver,Nuggets,Denver,DEN,Denver,1163.0,4.0,24.0,1147.0,4.0,33.0,1147.0,3.0,33.0,1163.0,3.0,25.0,1163.0,2.0,43.0,1147.0,2.0,21.0,1163.0,1.0,27.0,1147.0,1.0,35.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1824,5,5,36546,4667830,Dallas Mavericks@Denver Nuggets,Denver,USA,complete,2023-02-16T09:00:00+07:00,Undefined,8,REG,None,1147,True,Denver,Nuggets,Denver,DEN,Denver,1154,False,Dallas,Mavericks,Dallas,DAL,Dallas,1154.0,4.0,35.0,1147.0,4.0,26.0,1147.0,3.0,31.0,1154.0,3.0,30.0,1147.0,2.0,35.0,1154.0,2.0,19.0,1147.0,1.0,26.0,1154.0,1.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1825,5,5,36546,4667920,Brooklyn Nets@Chicago Bulls,Chicago,USA,complete,2023-02-25T08:00:00+07:00,Undefined,8,REG,None,1169,False,Brooklyn,Nets,Brooklyn,BKN,Brooklyn,1167,True,Chicago,Bulls,Chicago,CHI,Chicago,1169.0,4.0,36.0,1167.0,4.0,34.0,1167.0,3.0,34.0,1169.0,3.0,22.0,1169.0,2.0,11.0,1167.0,2.0,30.0,1167.0,1.0,33.0,1169.0,1.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1826,5,5,36546,4667916,Oklahoma City@Phoenix Suns,Phoenix,USA,complete,2023-02-25T10:00:00+07:00,Undefined,8,REG,None,1149,True,Phoenix,Suns,Phoenix,PHX,Phoenix,1145,False,Oklahoma City,Thunder,Oklahoma City,OKC,Oklahoma City,1149.0,4.0,30.0,1145.0,4.0,28.0,1149.0,3.0,29.0,1145.0,3.0,27.0,1149.0,2.0,36.0,1145.0,2.0,30.0,1145.0,1.0,30.0,1149.0,1.0,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1827,5,5,36546,4668002,Minnesota Timberwolves@Golden State,San Francisco,USA,complete,2023-02-27T07:30:00+07:00,Undefined,8,REG,None,1152,True,Golden State,Warriors,Golden State,GSW,Golden State,1144,False,Minnesota,Timberwolves,Minnesota,MIN,Minnesota,1152.0,4.0,31.0,1144.0,4.0,17.0,1144.0,3.0,30.0,1152.0,3.0,19.0,1152.0,2.0,34.0,1144.0,2.0,23.0,1144.0,1.0,34.0,1152.0,1.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1828,5,5,36546,4668171,Utah Jazz@Oklahoma City,Oklahoma City,USA,complete,2023-03-04T08:00:00+07:00,Undefined,8,REG,None,1145,True,Oklahoma City,Thunder,Oklahoma City,OKC,Oklahoma City,1143,False,Utah,Jazz,Utah,UTA,Utah,1143.0,4.0,19.0,1145.0,4.0,33.0,1145.0,3.0,30.0,1143.0,3.0,32.0,1145.0,2.0,33.0,1143.0,2.0,23.0,1145.0,1.0,34.0,1143.0,1.0,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [193]:
merged2_df = pd.merge(df2_ol, df_e_2, how='inner', on='event id')[['event id', 'market id', 'description', 'location', 'datetime_x', 'decimal odds', 'american odds', 'spread / total', 'participants.1.participant id', 'participants.1.source.nickname', 'participants.1.source.short name', 'participants.2.participant id', 'participants.2.source.nickname', 'participants.2.source.short name']]

In [194]:
merged2_df

,event id,market id,description,location,datetime_x,decimal odds,american odds,spread / total,participants.1.participant id,participants.1.source.nickname,participants.1.source.short name,participants.2.participant id,participants.2.source.nickname,participants.2.source.short name
0,4531898,402,Cleveland Cavaliers@Miami Heat,Miami,2022-03-11T21:36:13+07:00,1.9524,-105,211.0,1158,Heat,Miami,1166,Cavaliers,Cleveland
1,4531898,402,Cleveland Cavaliers@Miami Heat,Miami,2022-03-11T21:36:13+07:00,1.9524,-105,211.0,1158,Heat,Miami,1166,Cavaliers,Cleveland
2,4531898,83,Cleveland Cavaliers@Miami Heat,Miami,2022-03-11T21:36:13+07:00,1.3774,-265,0.0,1158,Heat,Miami,1166,Cavaliers,Cleveland
3,4531898,83,Cleveland Cavaliers@Miami Heat,Miami,2022-03-11T21:36:13+07:00,3.3100,231,0.0,1158,Heat,Miami,1166,Cavaliers,Cleveland
4,4531898,401,Cleveland Cavaliers@Miami Heat,Miami,2022-03-11T21:36:13+07:00,1.9524,-105,-7.0,1158,Heat,Miami,1166,Cavaliers,Cleveland
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10931,4693181,401,Team Giannis@Team LeBron,Salt Lake City,2023-02-17T20:04:15+07:00,1.9434,-106,-3.0,317684,LeBron,Team LeBron,317683,Giannis,Team Giannis
10932,4693441,83,Team Pau@Team Deron,Salt Lake City,2023-02-18T08:19:21+07:00,1.7692,-130,0.0,588026,Team Pau,Team Pau,588027,Team Deron,Team Deron
10933,4693441,83,Team Pau@Team Deron,Salt Lake City,2023-02-18T08:19:21+07:00,2.1100,111,0.0,588026,Team Pau,Team Pau,588027,Team Deron,Team Deron
10934,4693444,83,Team Joakim@Team Jason,Salt Lake City,2023-02-18T08:19:21+07:00,2.4000,140,0.0,588029,Team Joakim,Team Joakim,588028,Team Jason,Team Jason
10935,4693444,83,Team Joakim@Team Jason,Salt Lake City,2023-02-18T08:19:21+07:00,1.6061,-165,0.0,588029,Team Joakim,Team Joakim,588028,Team Jason,Team Jason

In [141]:
dt_start = datetime.strptime('2021-08-15', '%Y-%m-%d')
dt_end = datetime.strptime('2022-06-15', '%Y-%m-%d')

In [142]:
ef = EventsByDateRange(nba.league_id, dt_start, dt_end)

In [149]:
df_f = ef.dataframe()

In [161]:
olf_ps = OpeningLines(ef.ids(), nba.market_id('pointspread'), sb.id('pinnacle'))

In [163]:
olf_t = OpeningLines(ef.ids(), nba.market_id('Totals'), sb.id('pinnacle'))

In [164]:
olf_ml = OpeningLines(ef.ids(), nba.market_id('money-line'), sb.id('pinnacle'))

In [165]:
df_olpsf = olf_ps.dataframe()
df_oltf = olf_t.dataframe()
df_olmlf = olf_ml.dataframe()

In [166]:
df_olf = pd.concat([df_oltf, df_olmlf, df_olpsf], axis=0)

In [167]:
merged_df_f = pd.merge(df_olf, df_f, how='inner', on='event id')[['event id', 'market id', 'description', 'location', 'datetime_x', 'decimal odds', 'american odds', 'spread / total', 'participants.1.participant id', 'participants.1.source.nickname', 'participants.1.source.short name', 'participants.2.participant id', 'participants.2.source.nickname', 'participants.2.source.short name']]

In [168]:
merged_df_f

,event id,market id,description,location,datetime_x,decimal odds,american odds,spread / total,participants.1.participant id,participants.1.source.nickname,participants.1.source.short name,participants.2.participant id,participants.2.source.nickname,participants.2.source.short name
0,4531822,402,Brooklyn Nets@Milwaukee Bucks,Milwaukee,2021-10-19T04:10:42+07:00,1.9524,-105,237.5,1165,Bucks,Milwaukee,1169,Nets,Brooklyn
1,4531822,402,Brooklyn Nets@Milwaukee Bucks,Milwaukee,2021-10-19T04:10:42+07:00,1.9524,-105,237.5,1165,Bucks,Milwaukee,1169,Nets,Brooklyn
2,4531822,83,Brooklyn Nets@Milwaukee Bucks,Milwaukee,2021-10-19T04:10:42+07:00,2.1300,113,0.0,1165,Bucks,Milwaukee,1169,Nets,Brooklyn
3,4531822,83,Brooklyn Nets@Milwaukee Bucks,Milwaukee,2021-10-19T04:10:42+07:00,1.8065,-124,0.0,1165,Bucks,Milwaukee,1169,Nets,Brooklyn
4,4531822,401,Brooklyn Nets@Milwaukee Bucks,Milwaukee,2021-10-19T04:10:42+07:00,2.0000,-100,1.5,1165,Bucks,Milwaukee,1169,Nets,Brooklyn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8196,4644401,83,Boston Celtics@Golden State,San Francisco,2022-06-11T10:43:08+07:00,1.6329,-158,0.0,1152,Warriors,Golden State,1171,Celtics,Boston
8197,4644401,83,Boston Celtics@Golden State,San Francisco,2022-06-11T10:43:08+07:00,2.4200,142,0.0,1152,Warriors,Golden State,1171,Celtics,Boston
8198,4644401,401,Boston Celtics@Golden State,San Francisco,2022-06-11T10:43:08+07:00,1.9524,-105,-3.5,1152,Warriors,Golden State,1171,Celtics,Boston
8199,4644401,401,Boston Celtics@Golden State,San Francisco,2022-06-11T10:43:08+07:00,1.9524,-105,3.5,1152,Warriors,Golden State,1171,Celtics,Boston
8200,4532344,83,Sacramento Kings@San Antonio,San Antonio,2021-11-10T05:49:35+07:00,1.9804,-102,0.0,1153,Spurs,San Antonio,1150,Kings,Sacramento

In [198]:
merged_df_f['datetime_x'] = pd.to_datetime(merged_df_f['datetime_x']).dt.strftime('%Y-%m-%d %H:%M:%S')

In [217]:
merged_df

,event id,market id,description,location,datetime_x,decimal odds,american odds,spread / total,participants.1.participant id,participants.1.source.nickname,participants.1.source.short name,participants.2.participant id,participants.2.source.nickname,participants.2.source.short name
2728,3872538,401,Philadelphia 76ers@Indiana Pacers,Indianapolis,2019-12-31 03:54:47,1.9524,-105,1.0,1163,Pacers,Indiana,1172,76ers,Philadelphia
2729,3872538,401,Philadelphia 76ers@Indiana Pacers,Indianapolis,2019-12-31 03:54:47,1.9524,-105,-1.0,1163,Pacers,Indiana,1172,76ers,Philadelphia
2764,3872546,401,L.A. Clippers@Sacramento Kings,Sacramento,2019-12-31 03:55:32,1.9524,-105,6.5,1150,Kings,Sacramento,1151,L.A. Clippers,L.A. Clippers
2765,3872546,401,L.A. Clippers@Sacramento Kings,Sacramento,2019-12-31 03:55:32,1.9524,-105,-6.5,1150,Kings,Sacramento,1151,L.A. Clippers,L.A. Clippers
2724,3872538,402,Philadelphia 76ers@Indiana Pacers,Indianapolis,2019-12-31 03:56:34,1.9524,-105,211.5,1163,Pacers,Indiana,1172,76ers,Philadelphia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11871,4531914,83,Milwaukee Bucks@Orlando Magic,Orlando,2021-12-30 21:45:42,1.0840,-1191,0.0,1165,Bucks,Milwaukee,1161,Magic,Orlando
11904,4531923,402,Golden State@Denver Nuggets,Denver,2021-12-30 21:47:02,1.9804,-102,212.5,1147,Nuggets,Denver,1152,Warriors,Golden State
11905,4531923,402,Golden State@Denver Nuggets,Denver,2021-12-30 21:47:02,1.9259,-108,212.5,1147,Nuggets,Denver,1152,Warriors,Golden State
11906,4531923,83,Golden State@Denver Nuggets,Denver,2021-12-30 21:47:02,2.7200,172,0.0,1147,Nuggets,Denver,1152,Warriors,Golden State
11907,4531923,83,Golden State@Denver Nuggets,Denver,2021-12-30 21:47:02,1.5155,-194,0.0,1147,Nuggets,Denver,1152,Warriors,Golden State

In [202]:
merged_df['datetime_x'] = pd.to_datetime(merged_df['datetime_x']).dt.strftime('%Y-%m-%d %H:%M:%S')

In [203]:
merged2_df['datetime_x'] = pd.to_datetime(merged2_df['datetime_x']).dt.strftime('%Y-%m-%d %H:%M:%S')

In [213]:
merged_df = merged_df.sort_values('datetime_x')

In [214]:
merged2_df = merged2_df.sort_values('datetime_x')

In [216]:
final_df = pd.concat([merged_df, merged2_df], axis=0).sort_values('datetime_x')

In [ ]:
final_df.to_csv('sportsbook_2019-12-31_

In [210]:
merged_df_f.sort_values('datetime_x')

,event id,market id,description,location,datetime_x,decimal odds,american odds,spread / total,participants.1.participant id,participants.1.source.nickname,participants.1.source.short name,participants.2.participant id,participants.2.source.nickname,participants.2.source.short name
7342,4537374,402,Brooklyn Nets@L.A. Lakers,Los Angeles,2021-10-03 20:24:49,1.9174,-109,222.5,1169,Nets,Brooklyn,1148,L.A. Lakers,L.A. Lakers
7343,4537374,402,Brooklyn Nets@L.A. Lakers,Los Angeles,2021-10-03 20:24:49,1.9346,-107,222.5,1169,Nets,Brooklyn,1148,L.A. Lakers,L.A. Lakers
7344,4537374,83,Brooklyn Nets@L.A. Lakers,Los Angeles,2021-10-03 20:24:49,1.5780,-173,0.0,1169,Nets,Brooklyn,1148,L.A. Lakers,L.A. Lakers
7345,4537374,83,Brooklyn Nets@L.A. Lakers,Los Angeles,2021-10-03 20:24:49,2.4600,146,0.0,1169,Nets,Brooklyn,1148,L.A. Lakers,L.A. Lakers
7346,4537374,401,Brooklyn Nets@L.A. Lakers,Los Angeles,2021-10-03 20:24:49,1.9434,-106,-4.0,1169,Nets,Brooklyn,1148,L.A. Lakers,L.A. Lakers
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8195,4644401,402,Boston Celtics@Golden State,San Francisco,2022-06-11 10:43:08,1.9524,-105,212.5,1152,Warriors,Golden State,1171,Celtics,Boston
8196,4644401,83,Boston Celtics@Golden State,San Francisco,2022-06-11 10:43:08,1.6329,-158,0.0,1152,Warriors,Golden State,1171,Celtics,Boston
8197,4644401,83,Boston Celtics@Golden State,San Francisco,2022-06-11 10:43:08,2.4200,142,0.0,1152,Warriors,Golden State,1171,Celtics,Boston
8198,4644401,401,Boston Celtics@Golden State,San Francisco,2022-06-11 10:43:08,1.9524,-105,-3.5,1152,Warriors,Golden State,1171,Celtics,Boston
8199,4644401,401,Boston Celtics@Golden State,San Francisco,2022-06-11 10:43:08,1.9524,-105,3.5,1152,Warriors,Golden State,1171,Celtics,Boston